name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Setup Node.js environment
      uses: actions/setup-node@v4.0.1
    - name: Install Node.js
      run: |
        cd wwwroot/js/
        npm install

    - name: Build Node.js
      run: |
        cd wwwroot/js/
        npm run build

    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore

    - name: Publish for linux-x64
      run: dotnet publish -c Release -r linux-x64 --property:PublishDir=bin/publish_dist/linux-x64/ -p:PublishSingleFile=true --self-contained true
    - name: Publish for win-x64
      run: dotnet publish -c Release -r win-x64 --property:PublishDir=bin/publish_dist/win-x64/ -p:PublishSingleFile=true --self-contained true
    - name: Publish for linux-arm64
      run: dotnet publish -c Release -r linux-arm64 --property:PublishDir=bin/publish_dist/linux-arm64/ -p:PublishSingleFile=true --self-contained true
    - name: Publish for linux-arm
      run: dotnet publish -c Release -r linux-arm --property:PublishDir=bin/publish_dist/linux-arm/ -p:PublishSingleFile=true --self-contained true

    - name: 'Upload Artifact for linux-x64'
      uses: actions/upload-artifact@v3
      with:
        name: linux-x64
        path: bin/publish_dist/linux-x64/
        retention-days: 5
    - name: 'Upload Artifact for win-x64'
      uses: actions/upload-artifact@v3
      with:
        name: win-x64
        path: bin/publish_dist/win-x64/
        retention-days: 5
    - name: 'Upload Artifact for linux-arm64'
      uses: actions/upload-artifact@v3
      with:
        name: linux-arm64
        path: bin/publish_dist/linux-arm64/
        retention-days: 5
    - name: 'Upload Artifact for linux-arm'
      uses: actions/upload-artifact@v3
      with:
        name: linux-arm
        path: bin/publish_dist/linux-arm/
        retention-days: 5